version: "3.8"

services:
  db:
    image: postgres:16-alpine
    container_name: huffle-shuffle-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: huffle_shuffle_test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 3s
      retries: 60
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
